"""
instagram_uploader.py
─────────────────────
Uploads reels directly to Instagram via the Graph API.
Captions are generated by Gemini 2.5 Flash using prompts engineered
to maximise Instagram's 2025 algorithm signals:
  1. Sends (DM shares) — highest-weighted engagement signal
  2. Saves             — second highest
  3. Comments          — drives ranking and reply chains
  4. Replays           — boosted by strong hooks in first 2 seconds

SETUP: Set these two env-vars (or GitHub Secrets):
  INSTAGRAM_TOKEN    — long-lived Page access token
  INSTAGRAM_USER_ID  — your IG Business / Creator account ID
  GEMINI_API_KEY     — paste your key below (or set as env-var)
"""

import os, sys, time, json, random, requests

# ── CONFIG ─────────────────────────────────────────────────────────────────────
ACCESS_TOKEN   = os.environ.get("INSTAGRAM_TOKEN",   "")
IG_USER_ID     = os.environ.get("INSTAGRAM_USER_ID", "")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "AIz...")  # ← or paste key
# ──────────────────────────────────────────────────────────────────────────────

GRAPH_BASE = "https://graph.facebook.com/v21.0"
GEMINI_URL = (
    "https://generativelanguage.googleapis.com/v1beta"
    "/models/gemini-2.5-flash:generateContent"
)

# ── Telegram (optional) ───────────────────────────────────────────────────────
try:
    import telegram_notifier as _tg
    def _tg_phase(phase, detail=""): _tg.notify_upload_phase(phase, detail)
    def _tg_err(stage, err):        _tg.notify_error(stage, err)
except ImportError:
    def _tg_phase(phase, detail=""): pass
    def _tg_err(stage, err):         pass


# ══════════════════════════════════════════════════════════════════════════════
#  HASHTAG STRATEGY  — 8-10 targeted tags per post
#
#  Why fewer tags? Instagram's 2024-2025 guidance explicitly recommends
#  3-8 highly relevant hashtags over 20-30 generic ones. Over-tagging
#  triggers the spam filter and suppresses Reel distribution.
#
#  Strategy: 2 mega (discovery) + 3-4 mid (niche) + 2-3 micro (community).
#  Rotated each run so the account never repeats the exact same set.
# ══════════════════════════════════════════════════════════════════════════════

_TAGS_MEGA = [
    "#LearnEnglish",
    "#EnglishVocabulary",
    "#WordOfTheDay",
    "#PublicSpeaking",
    "#EnglishLearning",
]

_TAGS_MID = [
    "#SpeakingEnglish",
    "#EnglishFluency",
    "#VocabularyBuilder",
    "#SpokenEnglish",
    "#EnglishChallenge",
    "#IELTSVocabulary",
    "#EnglishSpeaking",
    "#FluentEnglish",
]

_TAGS_MICRO = [
    "#60SecondChallenge",
    "#WordChallenge",
    "#SpeakingChallenge",
    "#DailyEnglish",
    "#EnglishWithMe",
    "#VocabularyChallenge",
    "#LearnEnglishOnline",
    "#EnglishPractice",
]

def build_hashtags() -> str:
    """
    Returns a varied 9-tag set each run.
    Formula: 2 mega + 4 mid + 3 micro = 9 tags.
    """
    tags = (
        random.sample(_TAGS_MEGA,  2) +
        random.sample(_TAGS_MID,   4) +
        random.sample(_TAGS_MICRO, 3)
    )
    random.shuffle(tags)
    return " ".join(tags)


# ══════════════════════════════════════════════════════════════════════════════
#  CAPTION STYLES — engineered for algorithm signals
#
#  Each style is designed to trigger a specific engagement behaviour:
#    - Save  → "you'll want this later" framing
#    - Send  → "tag someone / send to a friend" CTA
#    - Comment → easy, low-friction prompt ("what's your sentence?")
#    - Replay  → strong opening hook that rewards re-watching
#
#  The first line of every style fits within Instagram's 125-character
#  preview (shown before the "more" cut-off in the feed).
# ══════════════════════════════════════════════════════════════════════════════

CAPTION_STYLES = [
    (
        "Save-and-send hook",
        "Line 1 (hook, ≤125 chars): Start with 'Save this.' then one urgent "
        "reason why knowing {word} will help them in a real conversation today.\n"
        "Line 2: Plain one-line definition in your own words.\n"
        "Line 3: One sentence — a vivid, real-world context where this word gives "
        "an instant advantage (job interview, first impression, debate).\n"
        "Line 4: 'Send this to someone learning English — they need this word.'\n"
        "Line 5: 'Timer is on screen. Say it out loud. Drop your sentence below 👇'",
    ),
    (
        "Curiosity gap + send",
        "Line 1 (hook, ≤125 chars): Ask a curiosity-gap question that {word} "
        "answers — make it feel uncomfortable NOT to know the answer.\n"
        "Line 2: Reveal {word} as the answer with a plain one-line definition.\n"
        "Line 3: One vivid example sentence using the word naturally.\n"
        "Line 4: 'Share this with a friend who wants to sound more confident.'\n"
        "Line 5: '60-second timer is on screen. Your sentence in the comments.'",
    ),
    (
        "Direct challenge",
        "Line 1 (hook, ≤125 chars): 'Can you use {word} in a sentence before "
        "the timer hits zero?' — pure urgency, no filler.\n"
        "Line 2: One punchy definition line.\n"
        "Line 3: One specific tip — the exact moment in daily life to use this word.\n"
        "Line 4: 'Save this so you never forget it.'\n"
        "Line 5: 'Timer is running. Go. Comment your sentence below.'",
    ),
    (
        "Micro story + save",
        "Lines 1-2 (hook, combined ≤125 chars visible): A 2-sentence story — "
        "someone is in a high-stakes moment (interview, presentation, first date) "
        "and reaches for the perfect word but goes blank.\n"
        "Line 3: Reveal {word} as the missing piece with a plain definition.\n"
        "Line 4: 'Save this reel so you have it when that moment comes.'\n"
        "Line 5: '60-second challenge is live on screen. Comment your sentence below 👇'",
    ),
    (
        "Social proof + send",
        "Line 1 (hook, ≤125 chars): 'Most fluent English speakers use this word "
        "every week — are you one of them?'\n"
        "Line 2: Reveal {word} with a one-line plain definition.\n"
        "Line 3: One sentence on why this specific word signals confidence and fluency.\n"
        "Line 4: 'Send this to someone who wants to level up their English.'\n"
        "Line 5: 'Live 60-second timer is on screen. Drop your sentence in the comments.'",
    ),
    (
        "Punchy and short",
        "Write the entire caption body in under 65 words.\n"
        "Line 1 (≤125 chars): {word} in ALL CAPS then a one-line power definition — "
        "make it impossible to scroll past.\n"
        "Line 2: One sentence on exactly when to use it.\n"
        "Line 3: 'Save this. Send it to a friend. Then comment your sentence below 👇'\n"
        "No filler. Every word must earn its place.",
    ),
]


def _strip_markdown(text: str) -> str:
    import re
    text = re.sub(r'\*{1,3}(.+?)\*{1,3}', r'\1', text)
    text = re.sub(r'_{1,2}(.+?)_{1,2}',   r'\1', text)
    text = re.sub(r'`(.+?)`',              r'\1', text)
    text = re.sub(r'^#+\s*',               '',    text, flags=re.MULTILINE)
    return text.strip()


def _call_gemini(prompt: str) -> str:
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature":     0.95,
            "topP":            0.92,
            "maxOutputTokens": 900,
        },
    }
    resp = requests.post(
        GEMINI_URL,
        params  = {"key": GEMINI_API_KEY},
        headers = {"Content-Type": "application/json"},
        json    = payload,
        timeout = 30,
    )
    data = resp.json()
    if resp.status_code != 200:
        raise RuntimeError(
            f"Gemini {resp.status_code}: "
            f"{data.get('error', {}).get('message', resp.text[:120])}"
        )
    try:
        return data["candidates"][0]["content"]["parts"][0]["text"].strip()
    except (KeyError, IndexError) as exc:
        raise RuntimeError(f"Bad Gemini response: {str(data)[:200]}") from exc


def _gemini_caption(word: str, pos: str, defn: str, hashtags: str) -> str:
    if not GEMINI_API_KEY or GEMINI_API_KEY.startswith("AIz..."):
        raise ValueError("GEMINI_API_KEY is not configured.")

    style_name, style_instructions = random.choice(CAPTION_STYLES)
    style_instructions = style_instructions.replace("{word}", word.upper())
    print(f"      Caption style : {style_name}")

    prompt = f"""Write an Instagram Reel caption. Follow the structure exactly.

REEL CONTEXT:
A 74-second educational reel. First 14 seconds: animated word reveal. Then a live 60-second countdown timer. Challenge: say a sentence using the word before the timer hits zero, then comment it below. The reel ends with "Follow for tomorrow's word."

AUDIENCE: Non-native English learners, ages 18-35, intermediate level (B1-B2). They want to sound fluent and confident in real situations. They respond strongly to challenges, save useful content, and share things that make them look smart.

ALGORITHM GOAL: This caption must drive Saves and Sends (DM shares) above all else, then Comments. These are Instagram's top-weighted engagement signals for Reels in 2025. Every line should push toward one of these actions.

WORD: {word.upper()} ({pos}) — {defn}

CAPTION STRUCTURE:
{style_instructions}

HARD RULES:
- First line must be ≤125 characters (it is the only line visible before the "more" button in the feed — make it impossible to scroll past).
- Put each section on its own line. Use a blank line between sections.
- No asterisks, hashtags, or markdown anywhere in the body.
- Maximum 2 emojis total in the body.
- No em-dashes. Use commas or short sentences.
- Do NOT start the caption with the word "{word}" alone on its own — lead with the hook.
- After the last body line, add one blank line, then write exactly:
{hashtags}

Write the complete caption now."""

    raw     = _call_gemini(prompt)
    caption = _strip_markdown(raw)

    if "#LearnEnglish" not in caption and _TAGS_MEGA[0] not in caption:
        caption = caption.rstrip() + "\n\n" + hashtags

    return caption


def build_caption(word: str, pos: str, defn: str) -> str:
    """Returns a Gemini-generated caption, falls back to static on failure."""
    hashtags = build_hashtags()
    try:
        caption = _gemini_caption(word, pos, defn, hashtags)
        print("  ✅  Caption generated.")
        return caption
    except Exception as exc:
        print(f"  ⚠️  Gemini failed ({exc}) — using fallback caption.")
        return (
            f"Save this. You'll want {word.upper()} in your next conversation.\n\n"
            f"({pos.capitalize()}) {defn}\n\n"
            f"Send this to a friend learning English — they need this word.\n\n"
            f"60-second timer is on screen. Say it out loud, then drop "
            f"your sentence in the comments 👇\n\n"
            f"{hashtags}"
        )


# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 1 — create upload container
# ══════════════════════════════════════════════════════════════════════════════
def init_upload_session(local_path: str, caption: str):
    file_size = os.path.getsize(local_path)
    print(f"  📋  Initialising upload session ({file_size/1024/1024:.1f} MB)…")
    _tg_phase("session", f"{file_size/1024/1024:.1f} MB — creating container…")

    resp = requests.post(
        f"{GRAPH_BASE}/{IG_USER_ID}/media",
        data={
            "media_type":    "REELS",
            "upload_type":   "resumable",
            "caption":       caption,
            "share_to_feed": "true",
            "access_token":  ACCESS_TOKEN,
        },
        timeout=30,
    )
    body = resp.json()

    if "error" in body:
        msg = (f"Session init failed (code {body['error'].get('code')}):\n"
               f"  {body['error'].get('message')}")
        _tg_err("Session init", msg)
        raise RuntimeError(msg)

    container_id = body.get("id")
    upload_url   = body.get("uri")

    if not container_id or not upload_url:
        msg = f"Missing id/uri in response:\n{json.dumps(body, indent=2)}"
        _tg_err("Session init", msg)
        raise RuntimeError(msg)

    print(f"  ✅  Container ID : {container_id}")
    return container_id, upload_url


# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 2 — upload video bytes
# ══════════════════════════════════════════════════════════════════════════════
def upload_video_bytes(local_path: str, upload_url: str) -> None:
    file_size = os.path.getsize(local_path)
    print(f"  ⬆️   Uploading {file_size/1024/1024:.1f} MB…")
    _tg_phase("uploading", f"{file_size/1024/1024:.1f} MB — sending bytes…")

    with open(local_path, "rb") as f:
        video_bytes = f.read()

    base_headers = {
        "offset":       "0",
        "file_size":    str(file_size),
        "Content-Type": "application/octet-stream",
    }

    for method, auth in [
        ("PUT",  f"OAuth {ACCESS_TOKEN}"),
        ("POST", f"OAuth {ACCESS_TOKEN}"),
        ("PUT",  f"Bearer {ACCESS_TOKEN}"),
        ("POST", f"Bearer {ACCESS_TOKEN}"),
    ]:
        headers = {**base_headers, "Authorization": auth}
        print(f"      Trying {method}…", end=" ")
        fn = requests.put if method == "PUT" else requests.post
        resp = fn(upload_url, headers=headers, data=video_bytes, timeout=300)
        print(f"→ HTTP {resp.status_code}")
        if resp.status_code in (200, 201):
            print("  ✅  Upload succeeded!")
            return

    msg = ("All upload attempts failed. Check that your token has "
           "'instagram_content_publish' permission and has not expired.")
    _tg_err("Video upload", msg)
    raise RuntimeError(msg)


# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 3 — wait for processing
# ══════════════════════════════════════════════════════════════════════════════
def wait_for_container(container_id: str, timeout: int = 300) -> None:
    print("  ⏳  Waiting for Instagram to process the video…")
    _tg_phase("processing", f"Container {container_id} — waiting…")

    endpoint = f"{GRAPH_BASE}/{container_id}"
    params   = {"fields": "status_code,status", "access_token": ACCESS_TOKEN}
    deadline = time.time() + timeout
    dots     = 0

    while time.time() < deadline:
        body   = requests.get(endpoint, params=params, timeout=30).json()
        status = body.get("status_code", "")
        dots  += 1
        print(f"      Status: {status or 'checking'} {'.' * (dots % 4)}   ", end="\r")

        if status == "FINISHED":
            print("\n  ✅  Processing complete.")
            return
        elif status == "ERROR":
            msg = f"Instagram rejected the video:\n{json.dumps(body, indent=2)}"
            _tg_err("Processing", msg)
            raise RuntimeError(msg)

        time.sleep(8)

    msg = f"Processing timed out after {timeout}s."
    _tg_err("Processing", msg)
    raise TimeoutError(msg)


# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 4 — publish
# ══════════════════════════════════════════════════════════════════════════════
def publish_container(container_id: str) -> str:
    print("  🚀  Publishing reel…")
    _tg_phase("publishing", f"Container {container_id} — calling media_publish…")

    body = requests.post(
        f"{GRAPH_BASE}/{IG_USER_ID}/media_publish",
        data={"creation_id": container_id, "access_token": ACCESS_TOKEN},
        timeout=60,
    ).json()

    if "error" in body:
        msg = (f"Publish failed (code {body['error'].get('code')}):\n"
               f"  {body['error'].get('message')}")
        _tg_err("Publish", msg)
        raise RuntimeError(msg)

    post_id = body["id"]
    print(f"  ✅  Post ID: {post_id}")
    return post_id


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════
def upload_reel(video_path: str, word: str, pos: str = "", defn: str = "",
                prebuilt_caption: str = None) -> str:
    if not ACCESS_TOKEN:
        raise ValueError("INSTAGRAM_TOKEN env-var not set.")
    if not IG_USER_ID:
        raise ValueError("INSTAGRAM_USER_ID env-var not set.")
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video not found: {video_path}")

    caption = prebuilt_caption if prebuilt_caption else build_caption(word, pos, defn)
    print(f"\n📝  Caption preview:\n{'─'*52}\n{caption[:350]}...\n{'─'*52}\n")

    container_id, upload_url = init_upload_session(video_path, caption)
    upload_video_bytes(video_path, upload_url)
    wait_for_container(container_id)
    return publish_container(container_id)


# ── STANDALONE ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python instagram_uploader.py <video.mp4> [word] [pos] [definition]")
        sys.exit(1)
    try:
        pid = upload_reel(
            sys.argv[1],
            sys.argv[2] if len(sys.argv) > 2 else "resilient",
            sys.argv[3] if len(sys.argv) > 3 else "adjective",
            sys.argv[4] if len(sys.argv) > 4 else "Able to recover quickly from difficult conditions.",
        )
        print(f"\n🎉  Reel is LIVE!  Post ID: {pid}")
    except Exception as e:
        print(f"\n❌  {e}")
        sys.exit(1)